"""Constants for the In2Games GameTrak HID device under investigation."""

GAMETRAK_VID = 0x14B7
GAMETRAK_PID = 0x0982

GAMETRAK_PRODUCT = "Game-Trak V1.3"
GAMETRAK_MANUFACTURER = "In2Games Ltd."

HID_USAGE_PAGE_GENERIC_DESKTOP = 0x01
HID_USAGE_JOYSTICK = 0x04

AXIS_LOGICAL_MIN = 0
AXIS_LOGICAL_MAX = 4095
EXPECTED_INPUT_REPORT_SIZE = 16
MIN_INPUT_REPORT_SIZE = 12
